[workspace]
members = [
    "contracts/token/psp20",
    "contracts/token/psp721",
    "contracts/token/psp1155",
    "contracts/access/ownable",
    "contracts/access/access-control",
    "contracts/security/reentrancy_guard",
    "contracts/brush",
]
exclude = [
    "examples",
    "mock"
]

[profile.release]
panic = "abort"
lto = true