[workspace]
members = [
    "contracts",
    "lang",
]

exclude = [
    "examples",
    "example_project_structure",
    "mock"
]

[package]
name = "openbrush"
version = "1.8.0"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2018"

license = "MIT"
readme = "README.md"
repository = "https://github.com/Supercolony-net/openbrush-contracts"
documentation = "https://docs.openbrush.io"
homepage = "https://supercolony.net"
description = "OpenBrush library for smart contract development on ink!."
keywords = ["wasm", "supercolony", "smart-contracts", "blockchain", "ink"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "lib.rs"]

[dependencies]
openbrush_contracts = { version = "1.8.0", path = "contracts", default-features = false }
openbrush_lang = { version = "1.8.0", path = "lang", default-features = false }

[lib]
name = "openbrush"
path = "lib.rs"
crate-type = [
    "rlib",
]

[features]
default = ["std"]
std = [
    "openbrush_contracts/std",
    "openbrush_lang/std",
]
psp22 = ["openbrush_contracts/psp22"]
psp34 = ["openbrush_contracts/psp34"]
psp1155 = ["openbrush_contracts/psp1155"]
ownable = ["openbrush_contracts/ownable"]
access_control = ["openbrush_contracts/access_control"]
payment_splitter = ["openbrush_contracts/payment_splitter"]
reentrancy_guard = ["openbrush_contracts/reentrancy_guard"]
pausable = ["openbrush_contracts/pausable"]
timelock_controller = ["openbrush_contracts/timelock_controller"]
proxy = ["openbrush_contracts/proxy"]
diamond = ["openbrush_contracts/diamond"]

[profile.release]
panic = "abort"
lto = true

[profile.dev]
panic = "abort"
lto = true
overflow-checks = false