[workspace]
members = [
    "contracts",
    "utils/brush_lang",
    "utils/brush_derive",
]

exclude = [
    "examples",
    "example_project_structure",
    "mock"
]

[package]
name = "brush"
version = "1.4.0"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2018"

[dependencies]
contracts = { path = "./contracts", default-features = false }
brush_lang = { path = "./utils/brush_lang", default-features = false }

[lib]
name = "brush"
path = "lib.rs"
crate-type = [
    "rlib",
]

[features]
default = ["std"]
std = [
    "contracts/std",
    "brush_lang/std",
]
psp22 = ["contracts/psp22"]
psp34 = ["contracts/psp34"]
psp1155 = ["contracts/psp1155"]
ownable = ["contracts/ownable"]
access_control = ["contracts/access_control"]
payment_splitter = ["contracts/payment_splitter"]
reentrancy_guard = ["contracts/reentrancy_guard"]
pausable = ["contracts/pausable"]
timelock_controller = ["contracts/timelock_controller"]
proxy = ["contracts/proxy"]

[profile.release]
panic = "abort"
lto = true
overflow-checks = false

[profile.dev]
panic = "abort"
lto = true
overflow-checks = false