[workspace]
members = [
    "contracts/token/psp20",
    "contracts/token/psp721",
    "contracts/token/psp1155",
    "contracts/access/ownable",
    "contracts/access/access-control",
    "contracts/brush",
    "contracts/brush/testing_utils"
]
exclude = [
    "examples",
    "mock"
]

[profile.release]
panic = "abort"
lto = true