[package]
name = "brush_lang"
version = "1.7.1"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2021"

[dependencies]
ink_env = { version = "3.2.0", default-features = false }
ink_lang = { version = "3.2.0", default-features = false }
ink_primitives = { version = "3.2.0", default-features = false }
ink_storage = { version = "3.2.0", default-features = false }
proc_macros = { path = "proc_macros" }
test_utils = { path = "test_utils", default-features = false }

[lib]
name = "brush_lang"
path = "lib.rs"
crate-type = [
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_env/std",
    "ink_lang/std",
    "ink_primitives/std",
    "ink_storage/std",
    "test_utils/std",
]