[package]
name = "testing_utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ink_env = { git = "https://github.com/Supercolony-net/ink", branch = "3.0-rc4", default-features = false }

scale = { package = "parity-scale-codec", version = "2.0", default-features = false, features = ["derive"] }
scale-info = { version = "0.6", default-features = false, features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
    "ink_env/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
]
ink-as-dependency = []


