[package]
name = "access_control_derive"
version = "0.3.0-rc1"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2018"

[dependencies]
syn = { version = "1.0" }
quote = "1.0"
proc-macro2 = "1"
brush_derive_macro = { path = "../../../../utils/brush_derive_macro" }

[lib]
name = "access_control_derive"
path = "lib.rs"
proc-macro = true

[features]
default = ["std"]
std = []