[package]
name = "flip_on_me"
version = "1.0.0"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc6", default-features = false }
ink_metadata = { version = "3.0.0-rc6", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc6", default-features = false }
ink_storage = { version = "3.0.0-rc6", default-features = false }
ink_lang = { version = "3.0.0-rc6", default-features = false }
ink_prelude = { version = "3.0.0-rc6", default-features = false }

scale = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
scale-info = { version = "1", default-features = false, features = ["derive"], optional = true }

# This dependencies
# We will do a cross contract call via `MyFlipper` wrapper imported here
reentrancy_guard = { path = "../../../contracts/security/reentrancy-guard", default-features = false }
my_flipper_guard = { path = "../flipper", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "flip_on_me"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",

    # This dependencies
    "my_flipper_guard/std",
    "reentrancy_guard/std",
]
ink-as-dependency = []

[profile.dev]
codegen-units = 16
