name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gokuseii/openbrush-contracts-ci
      options: --user root
      env:
        CARGO_TARGET_DIR: /usr/local/cache/target
    steps:
      - uses: actions/checkout@v2
      - name: Build & Run Cargo tests
        run: cargo test --release
      - name: Yarn install dependencies
        run: yarn
      - name: Redspot Ğ¡ompile
        run: |
          chown -R root .
          chmod -R a+rwx .
          yarn run build:release
      - name: Run Test Mocha
        run: |
          europa --tmp > /dev/null 2>&1 & P1=$!
          yarn run test:mocha & P2=$!
          wait $P2
          kill $P1